Brave Search API Implementation
langchain4j/langchain4j pull request #2188
Opened 2024-11-25 19:59 UTC by Suhas-Koheda

## Issue

Closes #2155

## Change

Implementation of the Brave search api configurations

## General checklist

- [x ] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

2024-11-25 20:00 UTC, Suhas-Koheda commented
@czelabueno hey! Hello! :-)
Can you please review

2024-11-25 20:12 UTC, Suhas-Koheda commented
@langchain4j while reading the pr template i had a doubt 
i have updated the aggregator pom with the brave module i have created 
is there any other place i should update the file or nothing?
thank you

2024-11-26 09:44 UTC, langchain4j reviewed
@Suhas-Koheda thank you! I have done a very brief review, but I will get back to this PR during the week

2024-11-26 09:44 UTC, langchain4j commented on web-search-engines/langchain4j-web-search-engine-tavily/src/main/java/dev/langchain4j/web/search/tavily/TavilyWebSearchEngine.java
> +public class    TavilyWebSearchEngine implements WebSearchEngine {
```suggestion
public class TavilyWebSearchEngine implements WebSearchEngine {
```

2024-11-26 09:44 UTC, langchain4j commented on web-search-engines/.idea/misc.xml
please remove all the `/.idea/` files from this PR, they should not be checked into git

2024-11-26 21:27 UTC, Suhas-Koheda commented on web-search-engines/.idea/misc.xml
Yeah i would be removing at my final commit 
Since I'll be opening in intellij continuously it'll be added every time 
So i let it be

2024-11-26 23:25 UTC, Suhas-Koheda commented
@langchain4j hey i had a doubt! 
I should just take the query and then show the results that's it right? 
Or should i do any other thing?

2024-11-27 04:02 UTC, czelabueno requested changes
Hi @Suhas-Koheda 
I just saw the great features that Brave has and I think it would be a good addition to the LC4J ecosystem.
According to the [documentation](https://api.search.brave.com/app/documentation/web-search/get-started) and reviewing the types of searches it supports and the current implementation of `WebSearchEngine` module, I think any Brave user could use these types of searches within LC4J:

- _Web Search API_ (https://api.search.brave.com/res/v1/web/search)
- _Summarizer Search API_ (https://api.search.brave.com/res/v1/summarizer/search) - I'm not sure about it, could you copy/paste in a comment the req/resp sample? If it's the API that return an summarization generated by AI with source links, can be useful. Similar to Taviliy. Anyway it'll be to confirm.
- _Search Image Search API_ (https://api.search.brave.com/res/v1/images/search)

The response of any of these search type can be parsed in a `WebSearchResults` object, similar to GoogleCustomSearch implementation. We could give to the user the option to search by web content/snippet OR images OR a AI summarization with metadata in order to add relevant content through `WebSearchContentRetriever` or as a `WebSearchTool`if the LLM supports it.

Refocus it and I did put some comments to code improvement :)

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveApi.java
> +            @Query("freshness") String freshness
I think these are not the only headers and parameters that a brave user can use. Does the `Api-Version` header depend on the type of search? is it useful?
Modify it so that a better `@QueryMap` can be entered.

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveApi.java
> +    @GET("search")
I'm not sure if this is right brave endpoint, anyway modify it to be able to set other search type

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveClient.java
> +public class BraveClient {
why is it a public class?

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveSearchDemo.java
remove and replace it with an IT

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveResponse.java
I think this class would change because of the first comments. It makes no sense for brave's req/resp classes to be public, they should be visible only within the brave package

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveWebSearchEngine.java
> +                .build();
try to use `WebSearchRequest` fields to pass params values. There several fields that make well match with `BreveWebSearchRquest`.

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveWebSearchEngine.java
> +     *                      Another example where only location results are required, set the result_filter param to result_filter=locations.
The LC4j core library only supports searching for web pages and images. Not news, videos, discussions, etc. Please document the current support.

2024-11-27 04:02 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveWebSearchEngine.java
> +    private static final String DEFAULT_BASE_URL = "https://api.search.brave.com/res/v1/web/";
The base URL should be the host URL, so it should be up to "https://api.search.brave.com"

2024-11-27 08:29 UTC, langchain4j commented on web-search-engines/.idea/misc.xml
It seems that your dev env is not configured right. There is a `.gitignore` in the root of the project to make sure that these files are not checked in. It will just make your life easier

2024-11-27 08:30 UTC, langchain4j commented
> @langchain4j hey i had a doubt!
> I should just take the query and then show the results that's it right?
> Or should i do any other thing?

Hi, I am not sure I understand the question, could you elaborate? Or did @czelabueno already answered it?

2024-11-27 09:58 UTC, Suhas-Koheda commented
@langchain4j solved! 
@czelabueno answered it 
Thank you!

2024-11-27 10:12 UTC, Suhas-Koheda commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveApi.java
> +            @Query("freshness") String freshness
So I'll make a query map in the client itself and call api right?

2024-11-28 01:45 UTC, czelabueno commented on web-search-engines/langchain4j-web-search-engine-brave/src/main/java/dev/langchain4j/web/search/brave/BraveApi.java
> +            @Query("freshness") String freshness
In order to leave to the user define which query param to search, you can take a look a [`SearchApi`](https://github.com/langchain4j/langchain4j/blob/cafeb93d6c9322ad74e22290caeee694f92e84e6/web-search-engines/langchain4j-web-search-engine-searchapi/src/main/java/dev/langchain4j/web/search/searchapi/SearchApi.java#L13)

2024-12-24 07:34 UTC, Martin7-1 commented
Should this PR migrate to [community](https://github.com/langchain4j/langchain4j-community) repo?

2024-12-27 16:44 UTC, Suhas-Koheda commented
@czelabueno hey i have completed the BraveWebSearchEngine 
I want you to have a look at it once 
I would be writing the tests in a couple of days 
But when i test myself without any structured tests they work!

2025-01-02 13:15 UTC, langchain4j commented
@Martin7-1 yes, makes sense!

@Suhas-Koheda could you please re-open this PR in the https://github.com/langchain4j/langchain4j-community repository please?

2025-02-19 15:45 UTC, Yayotron commented
Hi @Suhas-Koheda, I would like to use this feature! Do you need any help to proceed with the MR?

2025-02-19 15:57 UTC, Suhas-Koheda commented
@Yayotron 
Hey! 
I'll have to open this PR in the community repo 
And i believe i have done the skeletal part of web search engine 
But yeah 
I was busy with my works so was not able to completely work on this

2025-05-16 11:51 UTC, closed without merging