Fix PG Vector Index creation statement incorrect
langchain4j/langchain4j pull request #302
Opened 2023-11-20 15:52 UTC by pascalconfluent

Statement has been corrected:

```
                final String indexName = table + "_ivfflat_index";
                connection.createStatement().executeUpdate(String.format(
                        "CREATE INDEX IF NOT EXISTS %s ON %s " +
                                "USING ivfflat (embedding vector_cosine_ops) " +
                                "WITH (lists = %s)",
                        indexName, table, ensureGreaterThanZero(indexListSize, "indexListSize")));
```

2023-11-25 10:15 UTC, langchain4j requested changes
@pascalconfluent thanks a lot!

2023-11-25 10:15 UTC, langchain4j commented on langchain4j-pgvector/src/test/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingIndexedStoreIT.java
> +public class PgVectorEmbeddingIndexedStoreIT {
please extend it from EmbeddingStoreIT, it will inherit all necessary tests

2023-11-26 03:48 UTC, kevin-wu-os commented
@langchain4j - can we wait until the original bug reporter to verify the issue?
Or maybe find the real root cause.
See https://github.com/langchain4j/langchain4j/issues/283#issuecomment-1824843083 and also the official doc states index name is not a required field.

https://github.com/langchain4j/langchain4j/issues/283#issuecomment-1824755729

2023-12-04 15:13 UTC, ghost approved these changes

2023-12-04 15:13 UTC, merged