Support for WorkerAI Provider
langchain4j/langchain4j pull request #320
Opened 2023-11-28 01:12 UTC by clun

### Support for Worker AI
CloudFlare opened a Beta of a new service Called WorkerAI
https://developers.cloudflare.com/workers-ai/

They do provide a REST API for different operations.
- [Text Generation](https://developers.cloudflare.com/workers-ai/models/text-generation/)
- [Text-to-Image](https://developers.cloudflare.com/workers-ai/models/text-to-image/)
- [Text Embeddings](https://developers.cloudflare.com/workers-ai/models/text-embeddings/)- [Automatic Speech Recognition](https://developers.cloudflare.com/workers-ai/models/speech-recognition/)
- [Translation](https://developers.cloudflare.com/workers-ai/models/translation/)
- [Text Classification](https://developers.cloudflare.com/workers-ai/models/text-classification/)
- [Image Classification](https://developers.cloudflare.com/workers-ai/models/image-classification/)

This pull request proposes an implementation for `ChatModel`, `LanguageModel`, `EmbeddingModel` but also a new one `ImageModel` that can be applied for other image generation.

```java
public interface ImageModel {
    // Generate and get binary Content
    Response<byte[]> generate(String prompt);
    // Generate and save result to file
    Response<File> generate(String prompt, String destination);
```

A neat model available is Stable Diffusion XL

2023-12-04 15:47 UTC, msmygit approved these changes
Looks awesomely fantastic to me! 🚀 🎸

2023-12-05 15:24 UTC, langchain4j requested changes
@clun thank you a lot, you rock! I think noone added so much functionality at once yet 🚀

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/pom.xml
> +    <artifactId>langchain4j-worker-ai</artifactId>
What do you think about renaming it into `langchain4j-cloudflare-workers-ai`?

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/pom.xml
> +    <name>LangChain4j integration with CloudFlare WorkerAI</name>
nitpick: WorkerAI -> WorkersAI

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiChatModel.java
> +public class WorkerAiChatModel extends AbstractWorkerAIModel implements ChatLanguageModel {
Please rename Worker into Workers everywhere in the code, comments, etc.

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiChatModel.java
> +    public Response<AiMessage> generate(List<ChatMessage> messages, List<ToolSpecification> toolSpecifications) {
minor: this can be removed, default implementation takes care of throwing exception

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiChatModel.java
> +    public Response<AiMessage> generate(List<ChatMessage> messages, ToolSpecification toolSpecification) {
same here

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiChatModel.java
> +            if (retrofitResponse.body() == null) {
this case is already handled inside `processErrors`

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +     * Constructor with Builder.
I am not sure that many javadocs in this PR are useful, most of them do not contribute any new information

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +            if (retrofitResponse.body() == null) {
same here

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +            if (res.getShape().get(0) != 1) {
what about moving this into `res.ensureSingleVector()` ?

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +                floatArray[i] = embeddings.get(i); // Unboxing Float to float
you could use `Embedding.from(embeddings)` instead

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +                floatArray[i] = embedding.get(i); // Unboxing Float to float
same here

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +        if (retrofitResponse.body() == null) {
same here

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +                List<TextSegment> chunk = textSegments.subList(i, Math.min(textSegments.size(), i + chunkSize));
How about moving partitioning logic into `Util.partition(List<?> list, int partitionSize)`? Would also be great to have a test for a few scenarios (null, 0, 1, 99, 100, 101, 199, 200, 201 items, etc)

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/model/ImageModel.java
> +public interface ImageModel {
Please move `ImageModel` into `langchain4j-core` module, `dev.langchain4j.model.image` package, this will be also used by DALL-E integration by @Heezer

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/model/ImageModel.java
> +    Response<byte[]> generate(String prompt);
I think it would be better to return `Response<Image>` here and `Image` will encapsulate `byte[]` inside (for other cases it can be also `url` of the image). But the idea is the same, when you call `generate()` on an `ImageModel`, `Image` is returned, regardless of the format

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/model/ImageModel.java
> +    Response<File> generate(String prompt, String destination);
How about:
`Response<Void> generate(String prompt, Path destination);` <- assuming user does not need to manipulate the image in the code, he just wants to generate and store it locally. And even if he wants to manipulate it, he has a `Path` which he provided himself already, so he can use it directly
or
`Response<Image> generate(String prompt, Path destination);` <- gives a bit more flexibility: e.g. returning an `Image` as a url (e.g. for sending it to FE for immediate display), but still persisting it into destination

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/test/java/dev/langchain4j/model/workerai/WorkerAIEmbeddingModelIT.java
> +        Assertions.assertNotNull(out.content());
I would also add `assertThat(out.content().dimension()).isEqualTo(768);`

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/test/java/dev/langchain4j/model/workerai/WorkerAIEmbeddingModelIT.java
> +        data.add(new TextSegment("Sentence1", new Metadata()));
nitpick: you could use `TextSegment.from("Sentence1")`

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/test/java/dev/langchain4j/model/workerai/WorkerAIEmbeddingModelIT.java
> +        Assertions.assertNotNull(out.content());
please add a check that there are 2 embeddings in the response.
Ideally you could embed "hi" and "hello" and then do `assertThat(CosineSimilarity.between(out.content().get(0), out.content().get(1))).isBetween(0.9, 1.0);`

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/test/java/dev/langchain4j/model/workerai/WorkerAILanguageModelIT.java
> +        Response<String> joke = languageModel.generate("Tell me jokeC cloud");
nitpick: some corrupted text

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/test/java/dev/langchain4j/model/workerai/WorkerAILanguageModelIT.java
> +        Assertions.assertNotNull(joke);
please add a check that joke.content() is not empty

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/test/java/dev/langchain4j/model/workerai/WorkerAiImageModelIT.java
> +        String homeDirectory = System.getProperty("user.home");
please use [JUnit's temp directory](https://www.baeldung.com/junit-5-temporary-directory) instead

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/AbstractWorkerAIModel.java
> +public abstract class AbstractWorkerAIModel {
Would be awesome to allow user define `Duration timeout` and `Integer maxRetries` with sensible defaults (see `OpenAiChatModel` as example), but this can be added later

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiLanguageModel.java
> +            if (retrofitResponse.body() == null) {
same here

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiLanguageModel.java
> +    public Response<String> generate(Prompt prompt) {
why do you need to override default impl?

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiChatModel.java
> +    public Response<AiMessage> generate(@NonNull  ChatMessage... messages) {
Why do you need to override the default implementation from `ChatLanguageModel`?

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiEmbeddingModel.java
> +    public Response<Embedding> embed(String text) {
it seems that instead of duplicating the logic of `Response<List<Embedding>> embedAll(List<TextSegment> textSegments)` you could simply remove this and `Response<Embedding> embed(TextSegment textSegment)` methods and the default implementation will call `Response<List<Embedding>> embedAll(List<TextSegment> textSegments)` eventually

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/AbstractWorkerAIModel.java
> +            throw new IllegalArgumentException("Account identifier should not be null or empty");
nitpick: you could do `this.accountIdentifier = ensureNotBlank(accountIdentifier, "accountIdentifier")` instead

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/AbstractWorkerAIModel.java
> +            StringBuilder errorMessage = new StringBuilder("Failed to generate chat message:");
this method is used not only by chat model, so better to generalize the error message

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/AbstractWorkerAIModel.java
> +                        .reduce((a, b) -> a + "\n" + b)
minor: this can be simplified into `.collect(joining("\n"))`

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/AbstractWorkerAIModel.java
> +            log.error(errorMessage.toString());
why is it needed to both log and throw the same exception message?

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/WorkerAiImageGenerationRequest.java
> +    String destinationFile;
I guess `destinationFile` should be removed from this class

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/WorkerAiImageGenerationResponse.java
> +public class WorkerAiImageGenerationResponse
it seems that this class is not used anywhere, can be removed

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiChatModel.java
> +        return new Response<>(new AiMessage(generate(req)),null, FinishReason.STOP);
If WorkersAI do not provide a finish reason, I would better return null instead of STOP as it might not always be true.
Same for all other places where you return STOP.

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiImageModel.java
> +                InputStream inputStream = response.body().byteStream();
minor: the code inside if block can be extracted into a separate method

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiModelName.java
> +    public static final int MAX_TOKENS =  512;
Is this used somewhere?

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiModelName.java
> +    public static final String LLAMA2_7B_AWQ = "@hf/thebloke/codellama-7b-instruct-awq";
is it supposed to be llama or codellama?

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/WorkerAiModelName.java
> +    public static final String BAAI_EMBEDDING_SMALL = "@cf/baai/bge-small-en-v1.5";
minor: I would include versions of the models in the constant names as there is a high chance that another version will come soon

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/main/java/dev/langchain4j/model/workerai/client/AbstractWorkerAIModel.java
> +     * @see dev.langchain4j.model.workerai.WorkerAiModelName
copy-paste

2023-12-05 15:24 UTC, langchain4j commented on langchain4j-worker-ai/src/test/java/dev/langchain4j/model/workerai/WorkerAIChatModelIT.java
> +        Assertions.assertEquals("PARIS", chatModel.generate(conversation).content().text().toUpperCase());
nitpick: you could do `assertThat(response.content().text()).isEqualToIgnoringCase("Paris")` instead

2024-06-05 08:11 UTC, geoand commented
Any chance this can be rebooted?

2024-06-06 19:36 UTC, clun commented
Sure the lagnchain4j providers interfaces evolved quite a bit. 
I am using this code in production for a little while. Will give a try this week-end.

2024-06-07 08:02 UTC, langchain4j commented
>> lagnchain4j providers interfaces evolved quite a bit

Hmm... what interfaces?

2024-06-10 15:12 UTC, closed without merging

2024-06-10 23:53 UTC, clun commented
The image model did not exist at that time, I also had to find a way to support image editions and masks.
Here is the new tentative @geoand 
https://github.com/langchain4j/langchain4j/pull/1262