add milvus support
langchain4j/langchain4j pull request #58
Opened 2023-07-30 19:24 UTC by IuriiKoval

2023-08-02 08:50 UTC, langchain4j commented
@IuriiKoval great job, thanks a lot! Don't worry, most of the comments are minor things and stupid questions from me :D

2023-08-02 08:50 UTC, langchain4j requested changes

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> + * Data type of the data to insert must match the schema of the collection, otherwise Milvus will raise exception.
Could you please move all javadoc to `MilvusEmbeddingStore` (this class is still missing, please see `PineconeEmbeddingStore` as an example)? User of the library is not supposed to be interacting with `MilvusEmbeddingStoreImpl` directly.

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusClient.java
> +public class MilvusClient extends MilvusServiceClient {
Could you please make all classes that should not be exposed to the end user to be package private? You can move all classes from `embedding.util` to `embedding` package to make it possible.

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +    public MilvusEmbeddingStoreImpl(String host, int port, String databaseName, String uri, String token, long connectTimeoutMs, long keepAliveTimeMs, long keepAliveTimeoutMs, boolean keepAliveWithou
minor: would be more readable to arrange all parameters in a column with one parameter per row

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusClient.java
> +package dev.langchain4j.store.embedding;
Do we need this class? can't we use MilvusServiceClient directly?

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +    // minSimilarity is ignored
is it not supported by milvus?

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/CollectionRequestBuilder.java
> +                .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
Please move consistency and especially metric type to the constructor. User should be able to override these default values. Thanks!

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/CollectionRequestBuilder.java
> +                .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
same here

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/CollectionDescription.java
> +    public String getCollectionName() {
minor: could you please remove "get" part from getters to be consistent with the rest of the codebase? thanks!

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/Mapper.java
> +            float[] vector = queryForVector(milvusClient, collectionDescription, rowId);
Assuming that vector cannot be loaded together with the rest of the fields, I would avoid loading every vector in a loop by default. It can be very slow and in 99% of cases vector itself is not required by the user, usually just score and original content (or embedding id) is interesting for the user. It would be great to load vector together wit hthe rest of the fields in one go, but if it is not possible in Milvus, could you please make this loading in a loop configurable via constructor and disabled by default? Thanks a lot!

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/Mapper.java
> +            double score = resultsWrapper.getIDScore(0).get(i).getScore();
If there is no minSimilarity feature in milvus, could you please add manual filtering here? If score is below minSimilarity, we should ignore this result. Thanks!

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +    public MilvusEmbeddingStoreImpl(String host, int port, String databaseName, String uri, String token, long connectTimeoutMs, long keepAliveTimeMs, long keepAliveTimeoutMs, boolean keepAliveWithou
There are too many parameters to configure 😅 Does milvus provide defaults for some of those fields (like timeouts, etc)? It would be great to allow user to specify only the most essential parameters, without which it will not work. The rest of parameters should be optional (default values should be defined by milvus. If milvus does not define them, we need to come up with reasonable defaults and provide them from our side)

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> + * Meaning if your embedding service returns 2-dimensional array e.g. [0.0129503,0.0155482] the vector field in Milvus DB must also be 2-dimensional.
nitpick: could you please increase dimensions in the example to 384? 2 diminsions is very far from a real world scenario

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +        this.collectionDescription = collectionDescription;
Please add check for null: `ensureNotNull(collectionDescription, "collectionDescription")`. This is mandatory parameter, right? If it was not provided, it is better to fail right away during object creation than wait untill some operation will be called. Thanks

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +        loadCollectionInMemory(milvusClient, collectionDescription.getCollectionName());
Can there be a problem with calling `loadCollectionInMemory()` every time search is done? This operation is probably costly? If we will still be calling mulitple times, should we send `refresh=true` from second call onwards?

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/CollectionOperationsExecutor.java
> +        return new SearchResultsWrapper(response.getData().getResults());
could you please add a check for response.exception and response.status fields? I guess we need to throw exception in case search failed. Or retry search if error is temporary.

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/CollectionRequestBuilder.java
> +        List<String> searchOutputFields = Arrays.asList(collectionDescription.getIdFieldName(), collectionDescription.getScalarFieldName());
I am wondering, can we add vector field name here as well? So that there is no need to query vectors separately?

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/pom.xml
> +    <artifactId>langchain4j-milvus</artifactId>
minor: please add
```
<name>LangChain4j integration with Milvus</name>
```

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/CollectionOperationsExecutor.java
> +                .orElseThrow(() -> new RuntimeException(String.format("Cannot extract vector with the vector field name '%s'", collectionDescription.getVectorFieldName())));
minor: could you please include `collectionDescription` and `rowId` in error message as well? This will make debugging for the user much easier.

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/CollectionOperationsExecutor.java
> +            vector[j] = floatVector.getDataList().get(j);
minor: you could use `Embedding.from(floatVector.getDataList())`, this iteration is already implemented there

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/Generator.java
> +        Arrays.fill(arr, "");
Milvus does not allow inserting nulls into scalar fields?

2023-08-02 08:50 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/util/Mapper.java
> +            EmbeddingMatch<TextSegment> embeddingMatch = new EmbeddingMatch<>(rowId,
Sorry for stupid question but is `rowId` the same as `resultsWrapper.getFieldData(collectionDescription.getIdFieldName(), 0).get(i)`? Does milvus have its own ID for every record? Is it rowId? or rowId exists only during search and iterating results?

2023-08-02 20:25 UTC, IuriiKoval commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusClient.java
> +public class MilvusClient extends MilvusServiceClient {
done

2023-08-02 20:27 UTC, IuriiKoval commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +    public MilvusEmbeddingStoreImpl(String host, int port, String databaseName, String uri, String token, long connectTimeoutMs, long keepAliveTimeMs, long keepAliveTimeoutMs, boolean keepAliveWithou
done

2023-08-14 14:07 UTC, langchain4j approved these changes, later dismissed
Great job! 🥳

2023-08-14 14:07 UTC, langchain4j commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusCollectionDescription.java
> +        if (inputIsValid("collectionName", collectionName)) {
minor: you can use existing `ensureNotBlank` methods instead:

`this.collectionName = ensureNotBlank(collectionName, "collectionName");`

2023-08-14 14:07 UTC, langchain4j commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusOperationsParams.java
> +     * Metric types for binary vectors are not supported at he moment
tiny: he -> the

2023-08-14 14:07 UTC, langchain4j commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusOperationsParams.java
> +        if (!"STRONG".equals(input) && !"BOUNDED".equals(input) && !"EVENTUALLY".equals(input)) {
minor: can we use custom enum instead? this way we dont need to validate user's input and it is more clear to the user.

2023-08-14 14:07 UTC, langchain4j commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusOperationsParams.java
> +        if (!"L2".equals(input) && !"IP".equals(input)) {
minor: enum here as well?

2023-08-14 14:07 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/Generator.java
> +    public static String generateRandomId() {
minor: you can use existing `Utils.randomUUID()`

2023-08-14 14:07 UTC, langchain4j commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +    public static class MilvusEmbeddingStoreImplBuilder {
I guess this builder is not needed now?

2023-08-15 21:51 UTC, IuriiKoval commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusCollectionDescription.java
> +        if (inputIsValid("collectionName", collectionName)) {
done

2023-08-15 21:51 UTC, IuriiKoval commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusOperationsParams.java
> +     * Metric types for binary vectors are not supported at he moment
fixed

2023-08-15 21:52 UTC, IuriiKoval commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusOperationsParams.java
> +        if (!"STRONG".equals(input) && !"BOUNDED".equals(input) && !"EVENTUALLY".equals(input)) {
yeah, you are right!

2023-08-15 21:52 UTC, IuriiKoval commented on langchain4j/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusOperationsParams.java
> +        if (!"L2".equals(input) && !"IP".equals(input)) {
done

2023-08-15 21:52 UTC, IuriiKoval commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/Generator.java
> +    public static String generateRandomId() {
fixed

2023-08-15 21:53 UTC, IuriiKoval commented on langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/MilvusEmbeddingStoreImpl.java
> +    public static class MilvusEmbeddingStoreImplBuilder {
good catch. removed.

2023-08-18 18:36 UTC, langchain4j approved these changes
Great job @IuriiKoval! Thank you so much!

2023-08-18 18:36 UTC, langchain4j commented on langchain4j-milvus/pom.xml
> +        <version>0.18.0</version>
please update to 0.20.0, because build fails now

2023-08-18 18:38 UTC, merged